services:
  # Backend of the application (ASP.NET Core)
  fighter-manager:
    build:
      context: .
      dockerfile: FighterManager.Server/Dockerfile
    ports:
      - "${ASPNETCORE_APP_PORT_1}:${ASPNETCORE_APP_PORT_1}"
    environment:
        ASPNETCORE_ENVIRONMENT: "PRODUCTION"
        ASPNETCORE_APP_DB: "${ASPNETCORE_APP_DB}"
        ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION: "${ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION}"
        ASPNETCORE_APP_PORT: "${ASPNETCORE_APP_PORT_1}"
        CLIENT_APP_PORTS: "${CLIENT_APP_PORTS}"
        Jwt__Audience: "${JWT_AUDIENCE}"
        Jwt__Issuer: "${JWT_ISSUER}"
        Jwt__Key: "${JWT_KEY}"
        Authentication__Google__ClientId: "${GOOGLE_CLIENT_ID}"
        Authentication__Google__ClientSecret: "${GOOGLE_CLIENT_SECRET}"
        DOTNET_RUNNING_IN_CONTAINER: true
    networks:
      - appnet
  video-analysis:
    build:
      context: .
      dockerfile: VideoAnalysis.Server/Dockerfile
    ports:
      - "${ASPNETCORE_APP_PORT_2}:${ASPNETCORE_APP_PORT_2}"
    environment:
        ASPNETCORE_ENVIRONMENT: "PRODUCTION"
        ASPNETCORE_APP_DB: "${ASPNETCORE_APP_DB}"
        ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION: "${ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION}"
        ASPNETCORE_APP_PORT: "${ASPNETCORE_APP_PORT_2}"
        CLIENT_APP_PORTS: "${CLIENT_APP_PORTS}"
        YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
        GoogleCloud__ProjectId: "${GOOGLE_CLOUD_PROJECT_ID}"
        GoogleCloud__BucketName: "${GOOGLE_CLOUD_BUCKET_NAME}"
        GoogleCloud__ServiceAccountKeyPath: "/app/secrets/codejitsu-cloud-storage-service-account.json"
        GeminiVision__Location: "${GEMINI_VISION_LOCATION}"
        GeminiVision__Model: "${GEMINI_VISION_MODEL}"
        GeminiVision__VideoAnalysisPrompt: "${GEMINI_VISION_VIDEO_ANALYSIS_PROMPT}"
        Jwt__Audience: "${JWT_AUDIENCE}"
        Jwt__Issuer: "${JWT_ISSUER}"
        Jwt__Key: "${JWT_KEY}"
        DOTNET_RUNNING_IN_CONTAINER: "true"
        XAIGROK_API_KEY: "${XAIGROK_API_KEY}"
        XAIGROK_ENDPOINT: "${XAIGROK_ENDPOINT}"
    volumes:
      - ./secrets/gcs-key.json:/app/secrets/codejitsu-cloud-storage-service-account.json:ro
    networks:
      - appnet
  match-maker:
    build:
      context: .
      dockerfile: MatchMaker.Server/Dockerfile
    ports:
      - "${ASPNETCORE_APP_PORT_3}:${ASPNETCORE_APP_PORT_3}"
    environment:
        ASPNETCORE_ENVIRONMENT: "PRODUCTION"
        ASPNETCORE_APP_DB: "${ASPNETCORE_APP_DB}"
        ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION: "${ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION}"
        ASPNETCORE_APP_PORT: "${ASPNETCORE_APP_PORT_3}"
        CLIENT_APP_PORTS: "${CLIENT_APP_PORTS}"
        DOTNET_RUNNING_IN_CONTAINER: "true"
    networks:
      - appnet
  # Frontend of the application (React-Vite)
  app-client:
    build:
      context: ./CodeJitsu.Client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_APP_PORTS}"
    environment:
      ASPNETCORE_ENVIRONMENT: "PRODUCTION"
      ASPNETCORE_APP_DB: "${ASPNETCORE_APP_DB}"
      ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION: "${ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION}"
      CLIENT_APP_PORTS: "${CLIENT_APP_PORTS}"
      DOTNET_RUNNING_IN_CONTAINER: "true"
    volumes:
      - ./CodeJitsu.Client/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./CodeJitsu.Client/default.local.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fighter-manager
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
