services:
  fighter-manager:
    image: us-central1-docker.pkg.dev/codejitsu/codejitsu-repo/fighter-manager
    build:
      context: .
      dockerfile: FighterManager.Server/Dockerfile
    ports:
      - "${ASPNETCORE_APP_PORT_1}:${ASPNETCORE_APP_PORT_1}"
    env_file: .env
    environment:
      - ASPNETCORE_APP_DB=${SUPABASE_APP_DB}
    networks:
      - appnet

  video-sharing:
    image: us-central1-docker.pkg.dev/codejitsu/codejitsu-repo/video-sharing
    build:
      context: .
      dockerfile: VideoSharing.Server/Dockerfile
    ports:
      - "7081:7081"
    env_file: .env
    environment:
      - ASPNETCORE_APP_DB=${SUPABASE_APP_DB}
    volumes:
      # This path will be created by the deployment script on the VM
      - ./secrets/gcs-key.json:/app/secrets/codejitsu-cloud-storage-service-account.json:ro
    networks:
      - appnet

  app-client:
    image: us-central1-docker.pkg.dev/codejitsu/codejitsu-repo/app-client
    build:
      context: ./SampleAspNetReactDockerApp.Client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_APP_PORTS}"
    env_file: .env
    environment:
      - ASPNETCORE_APP_DB=${SUPABASE_APP_DB}
    volumes:
      - ./SampleAspNetReactDockerApp.Client/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fighter-manager
    networks:
      - appnet

networks:
  appnet:
    driver: bridge