services:
  # Database of the application (Postgres)
  app-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AppDb
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p "${POSTGRES_PORT}"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - appnet
  # Backend of the application (ASP.NET Core)
  app-api:
    build:
      context: .
      dockerfile: FighterManager.Server/Dockerfile
    ports:
      - "${ASPNETCORE_APP_PORT_1}:${ASPNETCORE_APP_PORT_1}"
    environment:
        ASPNETCORE_ENVIRONMENT: "PRODUCTION"
        ASPNETCORE_APP_DB: "${ASPNETCORE_APP_DB}"
        ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION: "${ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION}"
        ASPNETCORE_APP_PORT: "${ASPNETCORE_APP_PORT_1}"
        CLIENT_APP_PORTS: "${CLIENT_APP_PORTS}"
        POSTGRES_PORT: "${POSTGRES_PORT}"
    depends_on:
      - app-db
    networks:
      - appnet
  video-api:
    build:
      context: .
      dockerfile: VideoSharing.Server/Dockerfile
    ports:
      - "${ASPNETCORE_APP_PORT_2}:${ASPNETCORE_APP_PORT_2}"
    environment:
        ASPNETCORE_ENVIRONMENT: "PRODUCTION"
        ASPNETCORE_APP_DB: "${ASPNETCORE_APP_DB}"
        ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION: "${ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION}"
        ASPNETCORE_APP_PORT: "${ASPNETCORE_APP_PORT_2}"
        CLIENT_APP_PORTS: "${CLIENT_APP_PORTS}"
        POSTGRES_PORT: "${POSTGRES_PORT}"
        YOUTUBE_API_KEY: "${YOUTUBE_API_KEY}"
        GoogleCloud__ProjectId: "${GOOGLE_CLOUD_PROJECT_ID}"
        GoogleCloud__BucketName: "${GOOGLE_CLOUD_BUCKET_NAME}"
        GoogleCloud__ServiceAccountKeyPath: "/app/secrets/codejitsu-cloud-storage-service-account.json"
    secrets: # Optional: Use Docker Secrets for service account key
      - gcs_service_account_key
    volumes:
      - "D:/vu-repos/bjj-training/codejitsu-cloud-storage-service-account.json:/app/secrets/codejitsu-cloud-storage-service-account.json:ro" # Mount absolute path
    depends_on:
      - app-db
    networks:
      - appnet
  pair-api:
    build:
      context: .
      dockerfile: MatchMaker.Server/Dockerfile
    ports:
      - "${ASPNETCORE_APP_PORT_3}:${ASPNETCORE_APP_PORT_3}"
    environment:
        ASPNETCORE_ENVIRONMENT: "PRODUCTION"
        ASPNETCORE_APP_DB: "${ASPNETCORE_APP_DB}"
        ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION: "${ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION}"
        ASPNETCORE_APP_PORT: "${ASPNETCORE_APP_PORT_3}"
        CLIENT_APP_PORTS: "${CLIENT_APP_PORTS}"
        POSTGRES_PORT: "${POSTGRES_PORT}"
    depends_on:
      - app-db
    networks:
      - appnet
  # Frontend of the application (React-Vite)
  app-client:
    build:
      context: ./SampleAspNetReactDockerApp.Client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_APP_PORTS}"
    environment:
      ASPNETCORE_ENVIRONMENT: "PRODUCTION"
      ASPNETCORE_APP_DB: "${ASPNETCORE_APP_DB}"
      ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION: "${ASPNETCORE_SHOW_SWAGGER_IN_PRODUCTION}"
      # ASPNETCORE_APP_PORT: "${ASPNETCORE_APP_PORT_1}"
      CLIENT_APP_PORTS: "${CLIENT_APP_PORTS}"
    volumes:
      - ./SampleAspNetReactDockerApp.Client/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-api
    networks:
      - appnet
volumes:
  app_data:

secrets: # Define Docker Secrets
  gcs_service_account_key:
    file: ./secrets/service-account-key.json # Path to the key file on the host

networks:
  appnet:
    driver: bridge